repos:
    - repo: local
      hooks:
          - id: rustfmt
            name: Format with rustfmt
            entry: cargo fmt
            language: system
            types: [rust]
            pass_filenames: false

          - id: clippy
            name: Check with clippy
            entry: cargo clippy
            language: system
            types: [rust]
            pass_filenames: false
            args: ["--", "-D", "warnings"]

          - id: cargo-check
            name: Validate with cargo check
            entry: cargo check
            language: system
            types: [rust]
            pass_filenames: false